### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by seppzzz** [fromholdio/silverstripe-urlsegmenter#1]
Thanks for sharing this!
Some suggestions (hope I am not wrong)!

You need to put
use Fromholdio\URLSegmenter\Extensions\URLSegmenter;
into you DataObject

the function getSortableScope() does not exist :

class URLSegmenter:

```
public function generateURLSegment($increment = 0)
    {
        $scope = $this->getOwner()->hasMethod('getURLSegmenterScope')
            //? $this->getOwner()->getSortableScope() // does not exist !!!!!!!!!!!!!!!!
			? $this->getOwner()->getURLSegmenterScope()
            : get_class($this->getOwner())::get();
    ..................................................
    ..................................................
```

And: to make sure it will be a nice readable url : filter all special chars out from $Title: 

```
    $title = preg_replace("/[^0-9a-zA-Z_\s]/", "", $this->getOwner()->Title);

     //  $this->getOwner()->URLSegment = $filter->filter($this->getOwner()->Title);
	  $this->getOwner()->URLSegment = $filter->filter($title);


```

Thanks. Sepp.

**Comment by dizzystuff** [comment]
Hi @seppzzz , my apologies for a long delay in response. The 'SortableScope' hook bug was resolved in versions 1.1.0 / 2.0.1. Sorry about that.

Please also see newly released v3.0.0 for the latest processing of special characters. The module uses the inbuilt URLSegmentFilter, which means it's unnecessary to do that preg_replace, rather we pass the Title to the filter and it does that work (and more!) for us.

If you get the chance to look at v3.0.0 and still find opportunities to filter the characters further, I'm very happy to take a look and integrate ideas.

Cheers.
